name: Deploy site to gh-pages

on:
  push:
    branches: [ main ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout branch
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
      - name: Clean install dependencies
        run: npm ci
      - name: Build
        run: npm run build

  gh-pages-deploy:
    name: Deploying to gh-pages
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Deploy site
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          destination_dir: docs