name: Deploy site to gh-pages

on:
  push:
    branches: [ main ]

jobs:
  gh-pages-deploy:
    name: Deploying to gh-pages
    runs-on: ubuntu-latest

    steps:
    - name: Checkout branch
      uses: actions/checkout@v3
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: 'npm'
    - name: Clean install dependencies
      run: npm ci
    - name: Build site
      run: npm run build:site
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.ACCESS_TOKEN }}
        publish_dir: ./docs
        destination_dir: docs
        
      
